Added graph for monitoring instructions. Fixed how deployments are cleaned up by using the aws list-exports command, and checking against the current workflow ID.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -375,33 +375,24 @@ jobs:
     steps:
       - install-dependencies
       - run:
-          name: Remove old stacks
+          name: Remove previous deployment
           command: |
-            export STACKS=$(aws cloudformation describe-stacks --query 'Stacks[*].StackName' | \
-                jq -r '.[]' | \
-                egrep "udapeople-(frontend|backend)-" | \
-                grep -v "${CIRCLE_WORKFLOW_ID:0:7}")
-            echo "$STACKS"
-            for stack in $STACKS; do
+            export OldWorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
 
-              # Clean up frontend stack
-              if [[ $stack =~ udapeople-frontend-.* ]]
-              then
-                echo "Removing frontend stack: $stack"
-                ID=$(echo "$stack" | sed 's/udapeople-frontend-//')
-                BUCKET_URL="s3://udapeople-${ID}"
-                echo "Removing bucket: $BUCKET_URL"
-                aws s3 rb $BUCKET_URL --force
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${ID}"
-              fi
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
 
-              # Clean up backend stack
-              if [[ $stack =~ udapeople-backend-.* ]]
-              then
-                echo "Removing backend stack: $stack"
-                aws cloudformation delete-stack --stack-name $stack
-              fi
-            done
+            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]]
+            then
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            else
+              echo "Have the current ID $OldWorkflowID. Cannot remove the current stack"
+              exit 1
+            fi
 
 workflows:
   default:
